### ISSUE TITLE
Handle qs parsing errors

### ISSUE THREAD

**Issue by hueniverse** [daf-spr/hapi-qs#1]
Parsing can fail.

**Comment by dafortune** [comment]
Good catch! Thanks! Will add a `try catch` just in case. Anyway, could you point out any specific case that might cause a failure?

**Comment by hueniverse** [comment]
Just look at the qs code.

**Comment by dafortune** [comment]
Might be me but I don't see an obvious point of failure on qs code + it seems not to fail loudly to any of my (manual) tests, also don't see explicit error handling logic on body-parser [it might be up on the stack] (https://github.com/expressjs/body-parser/blob/master/lib/types/urlencoded.js#L216 + https://github.com/expressjs/body-parser/blob/master/lib/types/urlencoded.js#L129). 

Anyway, I just gave it a quick look, will give it a better look tomorrow.

**Comment by hueniverse** [comment]
@nlf can qs fail?

**Comment by nlf** [comment]
it shouldn't be able to

**Comment by dafortune** [comment]
Thanks @nlf. Let's close this issue for now then. Will re-open in case we find a failure point. 

Feel free to comment here if you think we need to add any kind of deeper error handling.

Thanks both! Happy holidays!

**Comment by dafortune** [comment]
Just for future reference, here a posible error handling code https://github.com/daf-spr/hapi-qs/pull/2
