### ISSUE TITLE
hapi-qs causes stripTrailingSlash option to not be respected

### ISSUE THREAD

**Issue by shane-walker** [daf-spr/hapi-qs#10]
It appears that there is a problem with hapi-qs that causes the `stripTrailingSlash` to not be respected, thus triggering 404 errors for users accessing with a trailing slash.

**Comment by dafortune** [comment]
Thanks for the feedback

**Comment by dafortune** [comment]
Published as hapi-qs@1.1.1 thanks @shane-walker
