### ISSUE TITLE
migrate to v17

### ISSUE THREAD

**Issue by dwelle** [daf-spr/hapi-qs#16]
https://github.com/hapijs/hapi/issues/3658

edit: provided there's any breaking changes related to this plugin -- haven't actually checked.

**Comment by dafortune** [comment]
Hi! Thanks,

I will check around this week (likely this weekend) and publish a new version for v17 support. PRs before that point are also welcome :)

**Comment by rajivm** [comment]
https://github.com/dafortune/hapi-qs/pull/17

**Comment by dafortune** [comment]
Published as 2.0.0
